[package]
name = "dns_load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
hickory-proto = "0.24.1"
lazy_static = "1.5.0"
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.26.0", features = ["default"] }
webpki-roots = "0.26.6"
