servers:
  - address: "1.1.1.1"
    use_tls: true
    description: "Cloudflare DNS"

  - address: "8.8.8.8"
    use_tls: true
    description: "Google DNS"

  - address: "10.152.183.10"
    use_tls: false
    description: "Kubernetes DNS"
