name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE: dns_load_balancer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker tag ${{ env.IMAGE }} ${{ env.USERNAME }}/${{ env.IMAGE }}:latest
          docker push ${{ env.USERNAME }}/${{ env.IMAGE }}:latest
